# Generated by Django 5.2.8 on 2026-01-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
    ]
